export const Menu = [
   {
     path: "/home",
     title: "900 * 2000 2 Panel Satine Paslanmaz Kat Mekanizması",
     icon: "folder-title-icon",
     class: "",
     label: "",
     labelClass: "",
     extralink: false,
     submenu: [
        {
             path: "/articleassociationconfig",
             title: "ARTICLE_ASSOCIATION",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        },
        {
             path: "/compatibilityloclu",
             title: "COMPATIBILITY_LOC_LU",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }, 
        {
             path: "/manageproductgroup",
             title: "PRODUCT_GROUP",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }, {
             path: "/manageproductsubgroup",
             title: "PRODUCT_SUB_GROUP",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }, {
             path: "/loadunitheighttype",
             title: "LOAD_UNIT_HEIGHT_TYPE",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }, {
             path: "/locationheighttype",
             title: "LOCATION_HEIGHT_TYPE",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }, {
             path: "",
             title: "MAP_REGISTRY",
             icon: "folder-title-icon",
             class: "has-arrow",
             label: "",
             labelClass: "label label-rouded label-themecolor pull-right",
             extralink: false,
             submenu: [{
                     path: "/managecarrier",
                     title: "CARRIERS",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/managesite",
                     title: "SITES",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/managedepartment",
                     title: "DEPARTMENTS",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/managearea",
                     title: "AREAS",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/managedevice",
                     title: "DEVICES",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/managelocation",
                     title: "LOCATIONS",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/logicalwh",
                     title: "LOGICAL_WH",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/logicalwhdecode",
                     title: "LOGICAL_WH_DECODE",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/logicalwhchangeconfig",
                     title: "LOGICAL_WH_CHANGE_CONFIG",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }, {
                     path: "/logicalwhtransaction",
                     title: "LOGICAL_WH_TRANSACTION",
                     icon: "file-title-icon",
                     class: "",
                     label: "",
                     labelClass: "",
                     extralink: false,
                     submenu: []
                }
            ]
        }
    ]
}, {
     path: "",
     title: "Setup",
     icon: "file-title-icon",
     class: "",
     label: "",
     labelClass: "",
     extralink: false,
     roles: ["PD0034_suppli"],
     submenu: [
        {
             path: "/logicalwhtransaction",
             title: "SETUP",
             icon: "file-title-icon",
             class: "",
             label: "",
             labelClass: "",
             extralink: false,
             submenu: []
        }
    ]
}
];